export = CodeGenerationResults;
/** @typedef {import("webpack-sources").Source} Source */
/** @typedef {import("./Module")} Module */
/** @typedef {import("./Module").SourceType} SourceType */
/** @typedef {import("./Module").CodeGenerationResult} CodeGenerationResult */
/** @typedef {import("./Module").CodeGenerationResultData} CodeGenerationResultData */
/** @typedef {import("./Module").ReadOnlyRuntimeRequirements} ReadOnlyRuntimeRequirements */
/** @typedef {typeof import("./util/Hash")} Hash */
/** @typedef {import("./util/runtime").RuntimeSpec} RuntimeSpec */
declare class CodeGenerationResults {
    /**
     * @param {string | Hash} hashFunction the hash function to use
     */
    constructor(hashFunction?: string | Hash);
    /** @type {Map<Module, RuntimeSpecMap<CodeGenerationResult>>} */
    map: Map<Module, RuntimeSpecMap<CodeGenerationResult>>;
    _hashFunction: string | typeof import("./util/Hash");
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @returns {CodeGenerationResult} the CodeGenerationResult
     */
    get(module: Module, runtime: RuntimeSpec): CodeGenerationResult;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @returns {boolean} true, when we have data for this
     */
    has(module: Module, runtime: RuntimeSpec): boolean;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @param {SourceType} sourceType the source type
     * @returns {Source} a source
     */
    getSource(module: Module, runtime: RuntimeSpec, sourceType: SourceType): Source;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @returns {ReadOnlyRuntimeRequirements | null} runtime requirements
     */
    getRuntimeRequirements(module: Module, runtime: RuntimeSpec): ReadOnlyRuntimeRequirements | null;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @param {string} key data key
     * @returns {ReturnType<CodeGenerationResultData["get"]>} data generated by code generation
     */
    getData(module: Module, runtime: RuntimeSpec, key: string): ReturnType<CodeGenerationResultData["get"]>;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @returns {string} hash of the code generation
     */
    getHash(module: Module, runtime: RuntimeSpec): string;
    /**
     * @param {Module} module the module
     * @param {RuntimeSpec} runtime runtime(s)
     * @param {CodeGenerationResult} result result from module
     * @returns {void}
     */
    add(module: Module, runtime: RuntimeSpec, result: CodeGenerationResult): void;
}
declare namespace CodeGenerationResults {
    export { Source, Module, SourceType, CodeGenerationResult, CodeGenerationResultData, ReadOnlyRuntimeRequirements, Hash, RuntimeSpec };
}
import { RuntimeSpecMap } from "./util/runtime";
type Source = import("webpack-sources").Source;
type Module = import("./Module");
type SourceType = import("./Module").SourceType;
type CodeGenerationResult = import("./Module").CodeGenerationResult;
type CodeGenerationResultData = import("./Module").CodeGenerationResultData;
type ReadOnlyRuntimeRequirements = import("./Module").ReadOnlyRuntimeRequirements;
type Hash = typeof import("./util/Hash");
type RuntimeSpec = import("./util/runtime").RuntimeSpec;
