export const require: '__webpack_require__';
export const requireScope: '__webpack_require__.*';
export const exports: '__webpack_exports__';
export const thisAsExports: 'top-level-this-exports';
export const returnExportsFromRuntime: 'return-exports-from-runtime';
export const module: 'module';
export const moduleId: 'module.id';
export const moduleLoaded: 'module.loaded';
export const publicPath: '__webpack_require__.p';
export const entryModuleId: '__webpack_require__.s';
export const moduleCache: '__webpack_require__.c';
export const moduleFactories: '__webpack_require__.m';
export const moduleFactoriesAddOnly: '__webpack_require__.m (add only)';
export const ensureChunk: '__webpack_require__.e';
export const ensureChunkHandlers: '__webpack_require__.f';
export const ensureChunkIncludeEntries: '__webpack_require__.f (include entries)';
export const prefetchChunk: '__webpack_require__.E';
export const prefetchChunkHandlers: '__webpack_require__.F';
export const preloadChunk: '__webpack_require__.G';
export const preloadChunkHandlers: '__webpack_require__.H';
export const definePropertyGetters: '__webpack_require__.d';
export const makeNamespaceObject: '__webpack_require__.r';
export const createFakeNamespaceObject: '__webpack_require__.t';
export const compatGetDefaultExport: '__webpack_require__.n';
export const harmonyModuleDecorator: '__webpack_require__.hmd';
export const nodeModuleDecorator: '__webpack_require__.nmd';
export const getFullHash: '__webpack_require__.h';
export const wasmInstances: '__webpack_require__.w';
export const instantiateWasm: '__webpack_require__.v';
export const uncaughtErrorHandler: '__webpack_require__.oe';
export const scriptNonce: '__webpack_require__.nc';
export const loadScript: '__webpack_require__.l';
export const createScript: '__webpack_require__.ts';
export const createScriptUrl: '__webpack_require__.tu';
export const getTrustedTypesPolicy: '__webpack_require__.tt';
export const hasFetchPriority: 'has fetch priority';
export const chunkName: '__webpack_require__.cn';
export const runtimeId: '__webpack_require__.j';
export const getChunkScriptFilename: '__webpack_require__.u';
export const getChunkCssFilename: '__webpack_require__.k';
export const hasCssModules: 'has css modules';
export const getChunkUpdateScriptFilename: '__webpack_require__.hu';
export const getChunkUpdateCssFilename: '__webpack_require__.hk';
export const startup: '__webpack_require__.x';
export const startupNoDefault: '__webpack_require__.x (no default handler)';
export const startupOnlyAfter: '__webpack_require__.x (only after)';
export const startupOnlyBefore: '__webpack_require__.x (only before)';
export const chunkCallback: 'webpackChunk';
export const startupEntrypoint: '__webpack_require__.X';
export const onChunksLoaded: '__webpack_require__.O';
export const externalInstallChunk: '__webpack_require__.C';
export const interceptModuleExecution: '__webpack_require__.i';
export const global: '__webpack_require__.g';
export const shareScopeMap: '__webpack_require__.S';
export const initializeSharing: '__webpack_require__.I';
export const currentRemoteGetScope: '__webpack_require__.R';
export const getUpdateManifestFilename: '__webpack_require__.hmrF';
export const hmrDownloadManifest: '__webpack_require__.hmrM';
export const hmrDownloadUpdateHandlers: '__webpack_require__.hmrC';
export const hmrModuleData: '__webpack_require__.hmrD';
export const hmrInvalidateModuleHandlers: '__webpack_require__.hmrI';
export const hmrRuntimeStatePrefix: '__webpack_require__.hmrS';
export const amdDefine: '__webpack_require__.amdD';
export const amdOptions: '__webpack_require__.amdO';
export const system: '__webpack_require__.System';
export const hasOwnProperty: '__webpack_require__.o';
export const systemContext: '__webpack_require__.y';
export const baseURI: '__webpack_require__.b';
export const relativeUrl: '__webpack_require__.U';
export const asyncModule: '__webpack_require__.a';
