permissions:
  # Permits `github/issue-labeler` to add a label to a pull request
  pull-requests: write
  contents: read

'change: feat':
  - '/^(feat|types|style)/'
'change: fix':
  - '/^fix/'
'change: perf':
  - '/^perf/'
'change: breaking':
  - '/^breaking change/'
'change: docs':
  - '/^docs/'
