packages:
  - '!**/dist/**'
  - 'packages/*'
  - 'packages/bridge/*'
  - 'packages/enhance'
  - 'apps/runtime-demo/*'
  - 'apps/next-app-router/*'
  - 'apps/modernjs-ssr/*'
  - 'apps/modern-component-data-fetch/*'
  - 'apps/router-demo/*'
  - 'apps/manifest-demo/*'
  - 'apps/esbuild'
  - 'apps/*'
  - 'apps/rsc-demo/*'
  - 'webpack'
  - 'assemble-release-plan'
  - 'packages/runtime-plugins/*'
