packages:
  - '!**/dist/**'
  - 'packages/*'
  - 'packages/bridge/*'
  - 'packages/enhance'
  - 'apps/runtime-demo/*'
  - 'apps/modernjs-ssr/*'
  - 'apps/router-demo/*'
  - 'apps/manifest-demo/*'
  - 'apps/esbuild'
  - 'apps/*'
  - 'webpack'
