import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { test } from 'node:test';
import {
  createReleaseDraft,
  withDownload,
  githubRequest,
} from './create-release-draft.mjs';
import { assetName } from './prepare-browser-release.mjs';

const archive = Buffer.from('browser extension ZIP fixture');
const metadata = {
  tag: 'v2.10.0',
  version: '2.10.0',
  extensionVersion: '2.10.0',
  sha: 'a'.repeat(40),
  channel: 'latest',
  asset: assetName,
  sha256: createHash('sha256').update(archive).digest('hex'),
};
const repository = 'module-federation/core';
const base = `/repos/${repository}`;
function host({
  existing = null,
  ref = null,
  target = metadata.sha,
  failUpload = false,
  assets = [],
  annotated = null,
} = {}) {
  const calls = [];
  let release = existing && structuredClone(existing);
  const request = async (route, options = {}) => {
    calls.push({ route, ...options });
    if (route.includes('/git/ref/tags/')) return ref;
    if (route.includes('/git/tags/')) return { object: annotated };
    if (route.includes('/commits/')) return { sha: target };
    if (route === `${base}/releases?per_page=100&page=1`)
      return release ? [release] : [];
    if (route === `${base}/releases/generate-notes`)
      return { body: '## Changes\nGenerated by GitHub' };
    if (route === `${base}/releases` && options.method === 'POST') {
      release = {
        id: 12,
        html_url:
          'https://github.com/module-federation/core/releases/tag/untagged-draft',
        ...options.body,
      };
      return release;
    }
    if (route === `${base}/releases/12/assets?per_page=100&page=1`)
      return assets;
    if (route === `${base}/releases/assets/77`) return archive;
    if (route.startsWith('https://uploads.github.com')) {
      if (failUpload) throw new Error('Upload interrupted');
      assets.push({
        id: 77,
        name: assetName,
        state: 'uploaded',
        digest: `sha256:${metadata.sha256}`,
      });
      return assets.at(-1);
    }
    if (route === `${base}/releases/12` && options.method === 'PATCH') {
      Object.assign(release, options.body);
      return release;
    }
    throw new Error(`Unexpected request: ${route}`);
  };
  return {
    request,
    calls,
    get release() {
      return release;
    },
    assets,
  };
}
const draft = () => ({
  id: 12,
  html_url: 'https://github.com/draft',
  tag_name: metadata.tag,
  target_commitish: metadata.sha,
  body: 'Hand-edited notes',
  draft: true,
  prerelease: false,
});
const run = (api, overrides = {}) =>
  createReleaseDraft({
    request: api.request,
    repository,
    metadata,
    archive,
    ...overrides,
  });
const mutations = (api) =>
  api.calls.filter((c) => c.method && c.method !== 'GET');

test('creates a draft with GitHub notes, explicit previous tag and exact source; attaches before linking', async () => {
  const api = host();
  await run(api, { previousTag: 'v2.9.0' });
  const notes = api.calls.find((c) => c.route.endsWith('/generate-notes'));
  assert.equal(notes.body.previous_tag_name, 'v2.9.0');
  assert.equal(notes.body.target_commitish, metadata.sha);
  assert.equal(notes.body.configuration_file_path, '.github/release.yml');
  assert.equal(api.release.draft, true);
  assert.equal(api.release.prerelease, false);
  assert.match(api.release.body, /Generated by GitHub/);
  assert.match(
    api.release.body,
    /releases\/download\/v2.10.0\/module-federation-devtools-browser.zip/,
  );
  const writes = mutations(api);
  assert.ok(
    writes.findIndex((c) => c.upload) <
      writes.findIndex((c) => c.method === 'PATCH'),
  );
  assert.ok(writes.every((c) => c.body?.draft !== false));
});

test('next creates a prerelease draft and leaves previous-tag selection to GitHub when omitted', async () => {
  const api = host();
  await run(api, {
    metadata: {
      ...metadata,
      version: '0.0.0-next-123',
      tag: 'v0.0.0-next-123',
      channel: 'next',
    },
  });
  assert.equal(api.release.prerelease, true);
  assert.equal(api.release.draft, true);
  assert.equal(
    api.calls.find((c) => c.route.endsWith('/generate-notes')).body
      .previous_tag_name,
    undefined,
  );
});

test('rerun preserves manual notes and matching assets without regenerating or uploading', async () => {
  const api = host();
  await run(api);
  api.release.body = 'Maintainer edits\n\n' + api.release.body;
  api.calls.length = 0;
  await run(api);
  assert.match(api.release.body, /^Maintainer edits/);
  assert.equal(mutations(api).length, 0);
  assert.equal(api.assets.length, 1);
});

test('upload failure leaves a draft which a retry resumes', async () => {
  const failed = host({ failUpload: true });
  await assert.rejects(run(failed), /Upload interrupted/);
  assert.equal(failed.release.draft, true);
  assert.doesNotMatch(failed.release.body, /Download Browser/);
  const retry = host({ existing: failed.release });
  await run(retry);
  assert.ok(!retry.calls.some((c) => c.route.endsWith('/generate-notes')));
  assert.match(retry.release.body, /Download Browser/);
});

test('published releases and mismatching tags/draft targets are never modified', async () => {
  for (const options of [
    { existing: { ...draft(), draft: false } },
    { existing: { ...draft(), immutable: true } },
    { ref: { object: { type: 'commit', sha: 'b'.repeat(40) } } },
    { existing: draft(), target: 'b'.repeat(40) },
    { existing: { ...draft(), prerelease: true } },
  ]) {
    const api = host(options);
    await assert.rejects(run(api));
    assert.equal(mutations(api).length, 0);
  }
});

test('checks the underlying commit of annotated tags', async () => {
  const api = host({
    ref: { object: { type: 'tag', sha: 'c'.repeat(40) } },
    annotated: { type: 'commit', sha: metadata.sha },
  });
  await run(api);
  assert.equal(api.release.target_commitish, metadata.sha);
});

test('verifies existing assets, downloading older assets without server digests', async () => {
  const api = host({
    existing: draft(),
    assets: [{ id: 77, name: assetName, state: 'uploaded' }],
  });
  await run(api);
  assert.ok(api.calls.some((c) => c.binary));
  assert.ok(!api.calls.some((c) => c.upload));
  const wrong = host({
    existing: draft(),
    assets: [{ name: assetName, state: 'uploaded', digest: 'sha256:wrong' }],
  });
  await assert.rejects(run(wrong), /differs/);
  assert.equal(mutations(wrong).length, 0);
});

test('corrupt local archive is rejected before any request', async () => {
  const api = host();
  await assert.rejects(
    run(api, { archive: Buffer.from('corrupted') }),
    /checksum/,
  );
  assert.equal(api.calls.length, 0);
});

test('managed download section is updated without duplicating or losing surrounding notes', () => {
  const body = withDownload('Hand-edited', repository, metadata) + '\nFooter';
  const updated = withDownload(body, repository, {
    ...metadata,
    extensionVersion: '2.10.1',
  });
  assert.match(updated, /^Hand-edited/);
  assert.match(updated, /Footer$/);
  assert.equal(updated.split('## Browser extension').length, 2);
  assert.match(updated, /2.10.1/);
  assert.throws(() =>
    withDownload('<!-- mf-browser-download:start -->', repository, metadata),
  );
});

test('API transport rejects foreign origins before transmitting credentials', async () => {
  await assert.rejects(
    githubRequest('test-only-token')('https://example.com/upload'),
    /origin/,
  );
});
