= Repositorio de GitHub Federaci贸n de M贸dulos con ejemplos y demos

En esta p谩gina encontrar谩 una lista de ejemplos y demos que muestran c贸mo funciona Federaci贸n de M贸dulos y c贸mo puedes utilizarla en distintos escenarios. Estos ejemplos y demos pretenden ayudarte a entender los conceptos y beneficios de la federaci贸n de m贸dulos, as铆 como proporcionarte algo de inspiraci贸n y orientaci贸n para tus propios proyectos.

== C贸mo utilizar el repositorio

El repositorio est谩 organizado en subcarpetas, cada una de las cuales contiene un ejemplo o demo espec铆fico de Federaci贸n de M贸dulos. Cada subcarpeta tiene su propio archivo README que explica el prop贸sito, instalaci贸n y configuraci贸n del ejemplo o demo. Puede navegar por las subcarpetas en GitHub o clonar el repositorio en su m谩quina local.

Para clonar el repositorio, ejecute el siguiente comando:

[source,bash]
----
git clone https://github.com/module-federation/module-federation-examples.git
----

Luego, vaya a la subcarpeta de su elecci贸n y siga las instrucciones del archivo README. La mayor铆a de los ejemplos y demos requieren que instale dependencias y ejecute un servidor de desarrollo utilizando comandos npm o yarn. Por ejemplo:

[source,bash]
----
cd basic-host-remote # cambia el directorio a la carpeta de ejemplo
npm install # instala las dependencias
npm start # inicia el servidor de desarrollo
----

A continuaci贸n, puede abrir su navegador y visitar las URL especificadas en el archivo README para ver el ejemplo o la demostraci贸n en acci贸n.

== Ejemplos y demos

1. ** Native Federation**: Demuestra Federaci贸n de M贸dulos usando esBuild, ESM, y Mapas de Importaci贸n, con el concepto aplicable tambi茅n a otros empaquetadores de m贸dulos. Aprenda c贸mo implementar Federaci贸n de M贸dulos de forma nativa sin Webpack.

2. ** Native Federation React**: Un ejemplo espec铆fico de React de Federaci贸n de M贸dulos utilizando esBuild, ESM y Mapas de Importaci贸n. Aplique la implementaci贸n nativa de Federaci贸n de M贸dulos en una aplicaci贸n React.

3. ** Advanced API**: Muestra el uso avanzado de la API en Federaci贸n de M贸dulos, destacando t茅cnicas que se pueden encontrar en otros ejemplos. Mejore su conocimiento de las caracter铆sticas avanzadas de Federaci贸n de M贸dulos.

4. ** Basic Host-Remote**: Ilustra c贸mo App 1 consume componentes remotos de la App 2 en una configuraci贸n hu茅sped-remoto simple. Comprende los conceptos fundamentales de la arquitectura hu茅sped-remoto de Federaci贸n de M贸dulos.

5. **Crear React App**: Aprenda a implementar Federaci贸n de M贸dulos dentro de un proyecto Create React App (CRA). Descubra c贸mo adaptar CRA para soportar Federaci贸n de M贸dulos.

6. ** Create React App with React App Rewired**: Implemente Federaci贸n de M贸dulos usando CRA y React App Rewired, una alternativa a la eyecci贸n de CRA. Explore una forma diferente de configurar CRA para Federaci贸n de M贸dulos sin eyecci贸n.

7. ** HMR Remotes**: Demuestra el Reemplazo de M贸dulos en Caliente (HMR) para remotos dentro de hu茅sped, permitiendo actualizaciones sin interrupci贸n de componentes remotos. Mejora la experiencia de desarrollo con actualizaciones en vivo.

8. ** Startup Code**: Presenta una implementaci贸n avanzada que adjunta c贸digo de inicializaci贸n al contenedor remoto. Este ejemplo es 煤til para establecer din谩micamente `publicPath` en el remoto, permitiendo un despliegue m谩s flexible.

9. **Dynamic Remotes in Node**: Aprenda a cargar remotos din谩micamente en un entorno Node.js, permitiendo la configuraci贸n en tiempo de ejecuci贸n de los componentes remotos.

10. **Bi-Directional Hosts**: Muestra c贸mo App 1 y App 2 consumen componentes la una de la otra, creando una relaci贸n bidireccional entre aplicaciones host. Explore escenarios avanzados hu茅sped-remoto.

11. **Self-Healing**: Implementa un mecanismo de contingencia a proveedores de aplicaciones remotas cuando una dependencia falla al cargarse. Mejora la resiliencia de las aplicaciones con capacidades de autocuraci贸n.

12. **Server-Side Rendering**: Demuestra c贸mo implementar Server-Side Rendering (SSR) con App 1 y App 2, permitiendo un mejor SEO y cargas de p谩gina iniciales m谩s r谩pidas.


13. **Server-Side Rendering (Simplified)**: Proporciona un c贸digo plantilla menos complejo para la implementaci贸n de SSR en Federaci贸n de M贸dulos, haci茅ndolo m谩s accesible a los desarrolladores.

14. 14. **Multi UI Framework Federation**: Muestra c贸mo federar m煤ltiples apps construidas con diferentes tecnolog铆as (React, Angular, Vue, etc.), permitiendo una integraci贸n fluida a trav茅s de frameworks UI.

15. 15. **Dynamic System Host**: Ense帽a c贸mo intercambiar entre remotos en tiempo de ejecuci贸n, permitiendo la carga din谩mica de componentes remotos basados en la interacci贸n del usuario u otros factores.

16. **Redux Reducer Injection**: Demuestra c贸mo inyectar reductores Redux din谩micamente en el almac茅n del hu茅sped en tiempo de ejecuci贸n, lo que permite una gesti贸n de estado modular y escalable.

17. **Shared Routes**: Ilustra la composici贸n de rutas federadas para una experiencia de usuario fluida, permitiendo la navegaci贸n entre aplicaciones federadas.

18. **Nested Components**: Aprenda a utilizar componentes remotos anidados en una configuraci贸n de Federaci贸n de M贸dulos, mostrando la flexibilidad de la composici贸n de componentes.

19. **Shared Context Provider**: Muestra c贸mo App 1 y App 2 pueden compartir un Proveedor de Contexto, permitiendo la gesti贸n de estados compartidos a trav茅s de aplicaciones federadas.

20. **Medusa Example**: Implementa un Panel de Control de Federaci贸n de M贸dulos con un 煤nico ejemplo, demostrando una aplicaci贸n pr谩ctica de Federaci贸n de M贸dulos.

21. **Non-UI Module**: Explora el uso de Federaci贸n de M贸dulos para componentes no-UI, como funciones de utilidad o m贸dulos de procesamiento de datos.

22. **Routing**: Ense帽a c贸mo compartir el contexto de enrutamiento entre aplicaciones federadas, lo que permite una navegaci贸n fluida. Un ejemplo adicional, Routing 2, proporciona t茅cnicas alternativas para compartir el contexto de enrutamiento.

23. **Version Discrepancy**: Maneja diferentes versiones de dependencias en apps federadas sin efectos secundarios. Aprenda a gestionar dependencias en aplicaciones federadas sin conflictos ni problemas de rendimiento.

24. **TypeScript**: Demuestra la transmisi贸n de TypeScript entre aplicaciones con federaci贸n de m贸dulos, lo que permite mejorar la seguridad de tipos y la experiencia del desarrollador.

25. **Angular Universal**: Presenta una aplicaci贸n remota y hu茅sped con Server-Side Rendering (SSR), m贸dulos y componentes con carga diferida, mostrando Federaci贸n de M贸dulos en una aplicaci贸n Angular Universal.

26. 26. **NextJS Sidecar Build**: Describe una compilaci贸n sidecar que habilita Federaci贸n de M贸dulos junto con bases de c贸digo Next.js, ilustrando la integraci贸n de Federaci贸n M贸dulos con Next.js.

27. **NextJS v12, v13**: Demuestra el funcionamiento de Federaci贸n de M贸dulos con las versiones 12 y 13 de Next.js utilizando el paquete `nextjs-mf`.

28. **NextJS**: Muestra el funcionamiento de Federaci贸n de M贸dulos con Next.js, utilizando el paquete `nextjs-mf` para integrar las dos tecnolog铆as.

29. **NextJS SSR**: Implementa el renderizado del lado del servidor con Next.js impulsado por flujos de software, utilizando el paquete `nextjs-ssr`.

30. **NextJS SSR via Delegates**: Proporciona c贸digo personalizado para contenedores y host utilizando `nextjs-ssr`, permitiendo una integraci贸n m谩s personalizada de Federaci贸n de M贸dulos y Next.js con Server-Side Rendering.

31. **Building a Plugin-based Workflow Designer**: Un ejemplo externo que demuestra c贸mo construir un dise帽ador de flujo de trabajo basado en plugins utilizando Angular y Federaci贸n de M贸dulos.

32. **Vue.js**: Ofrece un ejemplo sencillo de hu茅sped/remoto con Vue 3.0, utilizando funciones de renderizado o Single File Components (SFC). Aprenda a integrar Federaci贸n de M贸dulos con aplicaciones Vue 3.

33. **Vue 2 en Vue 3**: Demuestra una aplicaci贸n Vue 3 cargando un componente remoto de Vue 2, permitiendo compartir componentes entre versiones en un ecosistema Vue.js.

34. 34. **Vue2 SSR**: Muestra el uso de Federaci贸n de M贸dulos como servicio en un escenario de Server-Side Rendering con Vue 2.

35. **React & NextJS Host/Remote**: Presenta ejemplos de React y NextJS como hu茅sped/remoto, ilustrando las capacidades de Federaci贸n de M贸dulos tanto en aplicaciones React como NextJS.

36. **Different React Versions in Isolation**: Ofrece un ejemplo simple de hu茅sped/remoto donde las aplicaciones tienen diferentes versiones de React y ReactDOM y no comparten ninguna dependencia. Aprenda a manejar las discrepancias de versi贸n sin conflictos.



37. ** CSS Isolated Host and Remote**: Demuestra la prevenci贸n de fugas de CSS entre aplicaciones federadas, asegurando que el estilo permanece aislado de los componentes previstos.

38. **vue3-demo-federation-with-vite**: Muestra proyectos integrados con Webpack y Vite Federation, donde tanto Webpack como Vite desempe帽an los roles de hu茅sped y remoto.

39. **quasar-cli-vue3-webpack-javascript**: Ense帽a c贸mo integrar Federaci贸n de M贸dulos con aplicaciones Quasar que ejecutan Vue 3 usando Quasar CLI (JavaScript).

40. **UMD Federation**: Demuestra el soporte para importar m贸dulos remotos UMD, ampliando el rango de formatos de m贸dulos soportados.

41. **Modernjs**: Proporciona un ejemplo de uso b谩sico de Federaci贸n de M贸dulos con el framework Modern.js.

42. **Modernjs Medusa**: Ilustra el uso de Medusa con el framework Modern.js, demostrando la integraci贸n con un popular panel de control de Federaci贸n de M贸dulos.

== Resumen y conclusi贸n

En esta p谩gina de documentaci贸n, ha aprendido a utilizar el repositorio GitHub de Federaci贸n de M贸dulos, que contiene una colecci贸n de ejemplos y demos para diferentes casos de uso y escenarios de Federaci贸n de M贸dulos. Tambi茅n ha aprendido sobre los diversos aspectos y caracter铆sticas de Federaci贸n de M贸dulos, tales como compartir m贸dulos, carga din谩mica, comunicaci贸n, gesti贸n de errores, optimizaci贸n, pruebas, depuraci贸n y despliegue. Tambi茅n ha encontrado enlaces a otros recursos y tutoriales que le ayudar谩n a iniciarse en Federaci贸n de M贸dulos.

Esperamos que esta p谩gina de documentaci贸n le resulte 煤til e informativa. Si tiene alguna pregunta, comentario o sugerencia, no dude en abrir una incidencia o una solicitud de incorporaci贸n de cambios (pull request) en el [repositorio](https://github.com/module-federation/module-federation-examples). 隆Feliz programaci贸n! 
