antora:
  extensions:
    - require: antora-navigator-extension
      config_file: ./antora-navigator.yml
site:
  title: Module Federation Documentation
  start_page: component-b::index.adoc
  robots: allow
urls:
  html_extension_style: drop
content:
  sources:
    - url: https://github.com/module-federation/universe
      branches: main
    - url: https://github.com/omfgnuts/test-component-a.git
      branches: main
ui:
  bundle:
    url: ./../../dist/apps/docs-ui
    snapshot: false
  supplemental_files: ./../../node_modules/antora-navigator-extension/data/
output:
  dir: ./../../dist/apps/docs
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
runtime:
  fetch: true
