= @module-federation/typescript - v2.4.2

= Federated Types

This plugin enables *Typescript Types* support for Module Federated Components.

== Installation

[source, javascript]
----
$ npm i @module-federation/typescript

----

== Usage

Register the plugin in `webpack configuration (webpack.config.js)` file

[source, javascript]
----
import webpack from 'webpack';
const { FederatedTypesPlugin } = require('@module-federation/typescript');
const federationConfig = {
  name: 'my-app',
  filename: 'remoteEntry.js',
  exposes: {
    //...exposed components
    './Button': './src/Button',
    './Input': './src/Input',
  },
  remotes: {
    app2: 'app2@http://localhost:3002/remoteEntry.js', // or Just the URL 'http://localhost:3002/remoteEntry.js'
  },
  shared: ['react', 'react-dom'],
};
module.exports = {
  /* ... */
  plugins: [
    // ...
    new FederatedTypesPlugin({
      federationConfig,
      // ...
    }),
  ],
};

----

To enable verbose logging add folowing in webpack config:

[source, javascript]
----
infrastructureLogging: {
  level: 'log';
}

----

The Module Federation plugin is required to be registered separately from this plugin. The federation configuration provided to the Typescript plugin or Module Federation plugin can be different, as an example - to discern pure javascript remotes from Typescript remotes.

You need to register this plugin in both remote and host apps. The plugin will automatically create a directory named `@mf-types` in the host app - that contains all the types exported by the remote apps.

To have the type definitions automatically found for imports, add `paths` in `tsconfig.json`:

[source, javascript]
----
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["./@mf-types/*"]
    }
  }
}

----

`baseUrl` must also be set for `paths` to work properly

== Plugin Options

== Usage in Next.js

You need to manually pass the `federationConfig` object to the plugin. The `remotes` value should contain absolute path.

Sample code:

[source, javascript]
----
// next.config.js
const FederatedTypesPlugin = require('@module-federation/typescript');
module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.plugins.push(
      new FederatedTypesPlugin({
        federationConfig: {
          ...federationConfig,
          remotes: { app2: 'app2@http://localhost:3000/remoteEntry.js' },
        },
        // ...
      })
    );
    return config;
  },
};

----

=== Support

Drop me a message on twitter for support/feedback, or maybe just say Hi at https://twitter.com/prasannamestha[@prasannamestha]

=== Credits

Shoutout to https://twitter.com/ScriptedAlchemy[@ScriptedAlchemy]  for helping with the development of this plugin.

