require('next/head');
require('next/router');
require('next/link');
require('next/script');
require('next/image');
require('next/dynamic');
require('next/error');
require('next/amp');
require('styled-jsx');
require('styled-jsx/style');
require('next/image');
// require('react/jsx-dev-runtime');
require('react/jsx-runtime');
