const {
  FederationHost,
  registerGlobalPlugins,
  getRemoteEntry,
  getRemoteInfo,
  loadScript,
  loadScriptNode,
  init,
  loadRemote,
  loadShare,
  loadShareSync,
  preloadRemote,
  registerRemotes,
  registerPlugins,
  getInstance,
  FederationManager,
  //@ts-ignore
} = __webpack_require__.federation.runtime as typeof import('./index');

export {
  FederationHost,
  registerGlobalPlugins,
  getRemoteEntry,
  getRemoteInfo,
  loadScript,
  loadScriptNode,
  init,
  loadRemote,
  loadShare,
  loadShareSync,
  preloadRemote,
  registerRemotes,
  registerPlugins,
  getInstance,
  FederationManager,
};
