name: iOS E2E Tests
description: 'Runs iOS E2E tests'

inputs:
  app_name:
    description: 'Name of the app to test'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: true
        clean: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - uses: pnpm/action-setup@v4

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Set SKIP_DEVTOOLS_POSTINSTALL
      run: echo "SKIP_DEVTOOLS_POSTINSTALL=true" >> "$GITHUB_ENV"
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build metro packages
      run: npx nx run-many --targets=build --projects=tag:type:metro --parallel=3 --skip-nx-cache
      shell: bash

    - name: Install Maestro CLI and iOS Utilities
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        brew tap facebook/fb
        brew install facebook/fb/idb-companion
        echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      shell: bash

    - name: Local RNEF Setup
      shell: bash
      run: |
        RNEF_PATH="apps/${{ inputs.app_name }}/.rnef/cache"
        mkdir -p $RNEF_PATH
        echo "{\"githubToken\": \"${{ inputs.github_token }}\"}" > "$RNEF_PATH/project.json"

    - uses: callstackincubator/ios@v1
      with:
        github-token: ${{ inputs.github_token }}
        destination: 'simulator'
        scheme: 'MFExampleHost'
        configuration: 'Release'
        working-directory: './apps/${{ inputs.app_name}}'

    - name: E2E Prepare Script
      shell: bash
      run: |
        pnpm --filter ${{ inputs.app_name }} e2e:prepare:ios
        # Serve mini apps in the background
        pnpm --filter ${{ inputs.app_name }} e2e:serve:ios &

    - name: Run iOS E2E Tests
      run: |
        pnpm --filter ${{ inputs.app_name }} ios:release
        pnpm --filter ${{ inputs.app_name }} e2e:run:ios
      shell: bash

    - name: Upload Maestro Logs on Failure
      if: failure() # Runs only if any of the previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: maestro-logs-ios-${{ inputs.app_name }}
        path: ~/.maestro/tests/
