#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# 使用项目指定的 Node 版本（从 .nvmrc 读取）
[ -s "$NVM_DIR/nvm.sh" ] && nvm use

npm run lint-fix

git add .