# .github/workflows/e2e-node.yml
name: E2E Node Federation

on:
  workflow_call:

jobs:
  e2e-node:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Setup Node.js 20
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Export SKIP_DEVTOOLS_POSTINSTALL
        run: echo "SKIP_DEVTOOLS_POSTINSTALL=true" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check CI conditions
        id: check-ci
        run: node tools/scripts/ci-is-affected.mjs --appName=node-host,node-local-remote,node-remote,node-dynamic-remote-new-version,node-dynamic-remote,node-host-e2e --githubOutput=run-e2e

      - name: Restore Turborepo cache
        if: steps.check-ci.outputs.run-e2e == 'true'
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: .turbo/cache
          key: ${{ runner.os }}-turbo-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref_name }}-
            ${{ runner.os }}-turbo-

      - name: Install Cypress
        if: steps.check-ci.outputs.run-e2e == 'true'
        run: npx cypress install

      - name: Build shared packages
        if: steps.check-ci.outputs.run-e2e == 'true'
        run: pnpm run build:packages

      - name: E2E Node Federation
        if: steps.check-ci.outputs.run-e2e == 'true'
        run: pnpm run e2e:node
