# .github/workflows/e2e-modernjs.yml
name: E2E Test for ModernJS

on:
  workflow_call:

jobs:
  e2e-modern:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache Tool Downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-toolcache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-toolcache-

      - name: Set Playwright cache status
        run: |
          if [ -d "$HOME/.cache/ms-playwright" ] || [ -d "$HOME/.cache/Cypress" ]; then
            echo "PLAYWRIGHT_CACHE_HIT=true" >> $GITHUB_ENV
          else
            echo "PLAYWRIGHT_CACHE_HIT=false" >> $GITHUB_ENV
          fi

      - name: Install Pnpm
        run: |
          corepack prepare pnpm@10.18.1 --activate
          corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Set Nx SHA
        uses: nrwl/nx-set-shas@v3

      - name: Set SKIP_DEVTOOLS_POSTINSTALL environment variable
        run: echo "SKIP_DEVTOOLS_POSTINSTALL=true" >> $GITHUB_ENV

      - name: Install Dependencies
        run: pnpm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Build for All
        run: npx nx run-many --targets=build --projects=tag:type:pkg

      - name: Run condition check script
        id: check-ci
        run: node tools/scripts/ci-is-affected.mjs --appName=modernjs

      - name: E2E Test for ModernJS
        if: steps.check-ci.outcome == 'success'
        run: npx kill-port --port 4001 && npx nx run-many --target=test:e2e --projects=modernjs --parallel=1 && npx kill-port --port 4001

      - name: Kill ports
        run: npx kill-port --port 4001
