name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reply-labeled:
    if: github.repository == 'module-federation/core'
    runs-on: ubuntu-latest
    steps:
      - name: contribution welcome
        if: github.event.label.name == 'contribution welcome' || github.event.label.name == 'help wanted'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue edit "${ISSUE_NUMBER}" --repo "${REPO}" --remove-label "pending triage" || true
          gh issue edit "${ISSUE_NUMBER}" --repo "${REPO}" --remove-label "need reproduction" || true

      - name: need reproduction
        if: github.event.label.name == 'need reproduction'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: |
            Hello @${{ github.event.issue.user.login }}. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using a GitHub repository or [StackBlitz](https://stackblitz.com/). Issues marked with `need reproduction` will be closed if they have no activity within 5 days.
        run: |
          gh issue comment "${ISSUE_NUMBER}" --repo "${REPO}" --body "$BODY"
          gh issue edit "${ISSUE_NUMBER}" --repo "${REPO}" --remove-label "pending triage" || true
